# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#### THE FILE IS GENERATED BY SCRIPT SO DO NOT MODIFY IT MANUALLY! ####

PRODUCT_COPY_FILES += \
    device/sony/c2105/rootdir/root/init.sony.rc:root/init.sony.rc \
    device/sony/c2105/rootdir/root/logo.rle:root/logo.rle \
    device/sony/c2105/rootdir/root/fstab.sony:root/fstab.sony \
    device/sony/c2105/rootdir/root/ueventd.sony.rc:root/ueventd.sony.rc \
    device/sony/c2105/rootdir/root/init.sony.usb.rc:root/init.sony.usb.rc \
    device/sony/c2105/rootdir/system/etc/media_profiles.xml:system/etc/media_profiles.xml \
    device/sony/c2105/rootdir/system/etc/media_codecs.xml:system/etc/media_codecs.xml \
    device/sony/c2105/rootdir/system/etc/gps.conf:system/etc/gps.conf \
    device/sony/c2105/rootdir/system/etc/audio_policy.conf:system/etc/audio_policy.conf \
    device/sony/c2105/rootdir/system/etc/snd_soc_msm/snd_soc_msm_Sitar:system/etc/snd_soc_msm/snd_soc_msm_Sitar \
    device/sony/c2105/rootdir/system/etc/nfcee_access.xml:system/etc/nfcee_access.xml \
    device/sony/c2105/rootdir/system/etc/thermald.conf:system/etc/thermald.conf \
    device/sony/c2105/rootdir/system/etc/vold.fstab:system/etc/vold.fstab \
    device/sony/c2105/rootdir/system/usr/keychars/pmic8xxx_pwrkey.kcm:system/usr/keychars/pmic8xxx_pwrkey.kcm \
    device/sony/c2105/rootdir/system/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/cyttsp3-i2c.kl:system/usr/keylayout/cyttsp3-i2c.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/msm8930-sitar-snd-card_Button_Jack.kl:system/usr/keylayout/msm8930-sitar-snd-card_Button_Jack.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/keypad_8960.kl:system/usr/keylayout/keypad_8960.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/simple_remote_appkey.kl:system/usr/keylayout/simple_remote_appkey.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/pmic8xxx_pwrkey.kl:system/usr/keylayout/pmic8xxx_pwrkey.kl \
