#!/usr/bin/perl
# Copyright (C) 2013 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# IMPORT
use strict;
use warnings;

# CONSTANT
use constant MK_FILE => 'c2105-copy.mk';
use constant BLOB_FOLDER => 'device/sony/c2105/rootdir/';

my $header = <<HEADER;
# Copyright (C) 2013 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
HEADER

my $warning = <<WARNING;

#### THE FILE IS GENERATED BY SCRIPT SO DO NOT MODIFY IT MANUALLY! ####

WARNING

sub main() {
    my $mk = &MK_FILE;
    open(FH, "> $mk") or die("Error: could not open file $mk!");
    chdir('../../..');
    my $folder = &BLOB_FOLDER;
    my @files = `find $folder -type f`;
    print(FH $header);
    print(FH $warning);
    print(FH 'PRODUCT_COPY_FILES += \\', "\n");
    foreach my $file (@files) {
        chomp($file);
        my @temp = split(/$folder/, $file);
        my $out = $temp[1];
        print(FH "    $file:$out \\", "\n");
    }
    close(FH);
}

main();
